include: package:lints/recommended.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    - always_declare_return_types
    - avoid_relative_lib_imports
    - parameter_assignments
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_relative_imports
    - require_trailing_commas
    - sort_child_properties_last

analyzer:
  exclude:
    - "**/__brick__/**"
