name: assembler
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
