include: package:lints/recommended.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_relative_imports
    - avoid_relative_lib_imports
    - require_trailing_commas
    - parameter_assignments
    - prefer_final_in_for_each
    - prefer_final_fields
    - unnecessary_breaks
